"""Initial migration update created_at in models

Revision ID: 3d58f0916e68
Revises: 03f4483eb62c
Create Date: 2024-09-07 22:29:05.264079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d58f0916e68'
down_revision: Union[str, None] = '03f4483eb62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
